USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS FINLENS_ROLE;

CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

CREATE WAREHOUSE IF NOT EXISTS TRANSFORMING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE LOADING_WH TO ROLE FINLENS_ROLE;
GRANT USAGE ON WAREHOUSE TRANSFORMING_WH TO ROLE FINLENS_ROLE;
