CREATE DATABASE IF NOT EXISTS FINLENS_RAW;
CREATE DATABASE IF NOT EXISTS FINLENS_STAGING;
CREATE DATABASE IF NOT EXISTS FINLENS_INTERMEDIATE;
CREATE DATABASE IF NOT EXISTS FINLENS_MARTS;

CREATE SCHEMA IF NOT EXISTS FINLENS_RAW.PUBLIC;
CREATE SCHEMA IF NOT EXISTS FINLENS_STAGING.PUBLIC;
CREATE SCHEMA IF NOT EXISTS FINLENS_INTERMEDIATE.PUBLIC;
CREATE SCHEMA IF NOT EXISTS FINLENS_MARTS.PUBLIC;
