# ruff: noqa: E501
"""Deepened data-engineering wiki articles.

These entries reuse the exact titles, cluster values, and branch values of the
matching entries in ``wiki_content.ARTICLES`` so that a consumer merging the two
dictionaries (``ARTICLES`` first, then ``DE_ARTICLES``) overrides the shorter
originals with the longer encyclopedia bodies below. Facts here are taken from the
FinLens source tree (ingestion clients, ``src/finlens``, the dbt project, and the
Airflow DAGs); they are written in the platform's own terms rather than copied from
any upstream documentation.
"""

from __future__ import annotations

DE_ARTICLES = {
    "Source Policy Overview": {
        "cluster": "Source Layer",
        "branch": "Data Plumbing",
        "summary": "FinLens consumes four public sources under stable contracts: FDIC failed-bank events, FDIC Quarterly Banking Profile aggregates, FRED macroeconomic series, and a current-parent institution directory; each source has a defined grain, cadence, ingestion client, and known failure modes.",
        "body": (
            "The platform treats every source as a contract rather than a convenience. A contract names the "
            "grain (what one row means), the refresh cadence, the ingestion client that pulls it, the Bronze "
            "artefact layout it produces, and the failure modes it is known to throw. The four active sources "
            "are kept deliberately small because each additional source carries an ongoing maintenance cost "
            "that does not disappear after the first ingestion succeeds.\n"
            "\n"
            "## The active set\n"
            "\n"
            "The active source identifiers are configured through `FINLENS_ACTIVE_SOURCES`, which defaults to "
            "`fdic,fred,qbp,nic`. Each identifier maps to a dedicated client under `ingestion/`: "
            "[[FDIC BankFind]] for the failed-bank list (`ingestion/fdic.py`), [[FDIC Quarterly Banking Profile]] "
            "for industry aggregates (`ingestion/qbp.py`), [[FRED and ALFRED]] for macro series "
            "(`ingestion/fred.py`), and the [[National Information Center]] current-parent view "
            "(`ingestion/nic.py`). A fifth client, `ingestion/fdic_institutions.py`, pulls a per-institution "
            "Call Report panel for the machine-learning subsystem; it writes locally only and is not part of the "
            "four-source serving contract.\n"
            "\n"
            "## What every source has in common\n"
            "\n"
            "All four serving clients land their output as immutable Bronze JSON under "
            "`data/raw/source=<src>/ingestion_date=YYYY-MM-DD/<uuid>.json`. The `<uuid>` suffix means a re-run "
            "never overwrites a prior artefact, which is what makes ingestion safe to retry. Each client also "
            "validates its required configuration before doing any network work, through `Settings.require(...)`, "
            "so a missing key fails loudly rather than writing an empty file that looks like success. That "
            "readiness check is the first layer of the [[Data Quality Strategy]].\n"
            "\n"
            "## Sources outside the active set\n"
            "\n"
            "SEC/EDGAR, the Federal Reserve FR Y-9C, the FFIEC UBPR, and the Senior Loan Officer Opinion Survey "
            "are documented as considered-and-deferred rather than silently omitted. Each has a recorded reason "
            "(taxonomy drift, a second identifier system, an access path in migration, or narrow analytical "
            "value) and a tracked path back in if the trade-off changes. The governing principle is depth over "
            "breadth: the platform would rather model four sources thoroughly than ten sources shallowly. These "
            "four collectively feed the Stress Pulse, Failure Forensics, and Macro Transmission surfaces "
            "described under [[Streamlit Surfaces]], and the institution panel feeds the predictive work.\n"
            "\n"
            "## Why a contract and not a connector\n"
            "\n"
            "Public banking data changes shape over time: columns get renamed, endpoints migrate, and "
            "authentication mechanisms change. Treating each source as a contract isolates that volatility at "
            "the ingestion boundary, so a downstream change in shape becomes a Silver normalisation edit rather "
            "than a break in a user-visible chart. This is the same containment principle that drives "
            "[[Bronze, Silver, Intermediate, Gold]]."
        ),
    },
    "FDIC Quarterly Banking Profile": {
        "cluster": "Source Layer",
        "branch": "Data Plumbing",
        "summary": "The Quarterly Banking Profile feed supplies industry-aggregate banking facts pulled from the FDIC Banks Summary API, normalised at ingestion into a year-keyed quarterly shape and landed as Bronze JSON for the Stress Pulse surface.",
        "body": (
            "The Quarterly Banking Profile (QBP) is the FDIC's recurring aggregate read of the US banking "
            "industry. In FinLens it is the canonical source for industry-level facts such as net income, "
            "return on assets, net interest margin, noncurrent loan and net charge-off measures, total assets, "
            "total deposits, and total equity. The data feeds the Gold mart `marts.fct_stress_pulse`, which the "
            "Stress Pulse surface reads.\n"
            "\n"
            "## How it is pulled\n"
            "\n"
            "The client `ingestion/qbp.py` does not scrape the published QBP report. It calls the FDIC Banks "
            "Summary API through the URL held in `FDIC_QBP_SOURCE_URL`. The default request filters "
            "`STNAME:\"United States\"` across the year range 1985 to 2025 and projects the fields "
            "`YEAR,STNAME,ASSET,DEP,EQ,NETINC,NIM,DRLNLS,P9LNLS`, sorted ascending by year. Using the API "
            "rather than the bulk report gives per-field control and a stable, scriptable request surface. The "
            "client requires `fdic_qbp_source_url` to be present before it runs.\n"
            "\n"
            "## Normalisation at ingestion\n"
            "\n"
            "QBP is one of the two sources that does a normalisation pass inside the ingestion client rather "
            "than waiting for the Silver layer. `_normalize_fdic_summary` reads the API response, buckets each "
            "record by year into a `YYYYQ4` quarter label, and sums the per-state amounts into one industry "
            "row per year. From those sums it derives ratios: `roa` and `nim` as the relevant amount over total "
            "assets times one hundred, `noncurrent_rate` from `P9LNLS` over assets, and `nco_rate` from "
            "`DRLNLS` over assets, with dollar amounts rescaled to millions. Fields the summary endpoint does "
            "not carry, including `problem_banks`, `asset_yield`, `funding_cost`, `afs_losses`, and "
            "`htm_losses`, are emitted as null placeholders so the column contract stays complete and stable. "
            "The output is tagged `source_code` `FDIC_BANKS_SUMMARY`.\n"
            "\n"
            "## Bronze layout and cadence\n"
            "\n"
            "The client writes two artefacts: the normalised rows as a `.data.json` payload and a metadata "
            "manifest as the primary `.json` file, both under "
            "`data/raw/source=qbp/ingestion_date=YYYY-MM-DD/<uuid>...`. The manifest records the source URL, "
            "the ingest timestamp, the `artifact_path` pointer the serving layer follows, and the payload size "
            "in bytes. The Airflow DAG `dag_ingest_qbp` runs quarterly on cron `0 3 1 */3 *`. Quarterly is the "
            "right cadence because the FDIC publishes QBP roughly two months after each quarter closes, so more "
            "frequent polling would mostly re-fetch unchanged data.\n"
            "\n"
            "## Failure modes and deferral behaviour\n"
            "\n"
            "Known risks are API rate limits, occasional changes to available filter parameters, and historical "
            "revisions that update prior quarters. The first two are handled through retry and the "
            "environment-controlled `FDIC_QBP_SOURCE_URL` override; the third is handled by the immutable Bronze "
            "design, where each ingestion is a separate snapshot. When no source URL is configured, the "
            "pipeline status model marks the `qbp` flow as Not Activated rather than faking a value, which is "
            "described under [[Pipeline Status and Operational State]]. The aggregates this source produces are "
            "what the [[Reconciliation Against External Authority]] panel compares back to FDIC-published totals."
        ),
    },
    "FRED and ALFRED": {
        "cluster": "Source Layer",
        "branch": "Data Plumbing",
        "summary": "FRED supplies the macroeconomic series; the ingestion client uses a metadata watermark so that a series is re-downloaded only when its upstream last-updated timestamp changes, which makes the hourly schedule cheap and re-runs idempotent.",
        "body": (
            "FRED is the Federal Reserve Bank of St. Louis economic data service, and ALFRED is its "
            "vintage-aware counterpart for point-in-time observations. FinLens uses FRED for macroeconomic "
            "series that have stable identifiers and broad analytical applicability. The data lands in the Gold "
            "mart `marts.fct_financial_metrics` and drives the Macro Transmission surface.\n"
            "\n"
            "## The configured series\n"
            "\n"
            "The active series are configured through `FRED_SERIES_IDS`, which defaults to "
            "`UNRATE,DGS10,DGS2,BAA10Y,NFCI,CPIAUCSL`: the civilian unemployment rate, the 10-year and 2-year "
            "constant-maturity Treasury yields, the Moody's Baa corporate spread over the 10-year Treasury, the "
            "Chicago Fed National Financial Conditions Index, and the headline Consumer Price Index. The list "
            "is read through the `fred_series_id_list` settings property, so changing the series set is a "
            "configuration edit, not a code change. The base URL is `FRED_BASE_URL` "
            "(`https://api.stlouisfed.org/fred`), and `FRED_API_KEY` is required; the client calls "
            "`Settings.require(\"fred_api_key\")` and refuses to run without it.\n"
            "\n"
            "## Watermarked pulls\n"
            "\n"
            "`ingestion/fred.py` is the only client with a watermark, and it is the reason the schedule can run "
            "often. For each series it first calls the FRED `/series` metadata endpoint and reads the "
            "`last_updated` timestamp. It compares that against the persisted watermark held under the platform "
            "state key `fred_watermarks`. If the timestamp is unchanged, the run short-circuits and returns a "
            "result flagged `updated=False` without touching `/series/observations`. Only when the timestamp has "
            "moved does it fetch observations, write a Bronze artefact, and advance the watermark. This makes a "
            "re-run of an unchanged series a no-op rather than a redundant download, and it keeps repeated runs "
            "idempotent.\n"
            "\n"
            "## Bronze artefact shape\n"
            "\n"
            "Each updated series is written as a single Bronze JSON object under "
            "`data/raw/source=fred/ingestion_date=YYYY-MM-DD/<uuid>.json`. The object carries `source`, "
            "`series_id`, `ingested_at`, the full series `metadata` block, and the `observations` array. Because "
            "the serving layer keys on `series_id` and chooses the most recently ingested artefact per series, "
            "multiple historical Bronze files per series coexist without conflict.\n"
            "\n"
            "## Cadence and rationale\n"
            "\n"
            "The Airflow DAG `dag_ingest_fred` runs on `@hourly`. An hourly cadence would be wasteful for a "
            "naive client, but the watermark turns most hourly runs into cheap metadata checks while giving the "
            "lowest-latency view of when FRED actually updates each series. The interpretation of these series, "
            "including which mechanism each one captures, is covered under "
            "[[How to Read Macro Indicators in This Surface]]."
        ),
    },
    "National Information Center": {
        "cluster": "Source Layer",
        "branch": "Data Plumbing",
        "summary": "The current-parent institution view is sourced from the FDIC institutions API and deliberately restricted to a single current parent per institution, dropping NIC's richer dated lineage in exchange for a stable, traversal-free join.",
        "body": (
            "The National Information Center (NIC), operated by the Federal Reserve, is the official directory "
            "of US bank holding company structure. FinLens consumes a restricted view of that structure: "
            "current parent metadata only, with no historical lineage and no graph traversal.\n"
            "\n"
            "## What the client actually reads\n"
            "\n"
            "The current implementation of `ingestion/nic.py` does not call an NIC endpoint directly. It reads "
            "from the FDIC institutions API through the URL in `NIC_CURRENT_PARENT_SOURCE_URL`, which defaults "
            "to a request filtered on `ACTIVE:1`, projecting "
            "`CERT,NAME,ACTIVE,BKCLASS,STALP,REGAGNT,ASSET,DEP,ROA,ROE,DATEUPDT`, sorted by asset size "
            "descending. This gives the population of currently operating insured depository institutions along "
            "with the ownership-adjacent fields the platform needs. The client requires "
            "`nic_current_parent_source_url` before it runs.\n"
            "\n"
            "## Normalisation at ingestion\n"
            "\n"
            "Like QBP, NIC normalises inside the client. `_normalize_institutions` maps each FDIC record onto a "
            "fixed canonical row with `rssd_id`, `fdic_certificate_number`, `institution_name`, "
            "`current_parent_rssd_id`, `current_parent_name`, `active`, `charter_class`, `state`, "
            "`primary_regulator`, `total_assets`, `total_deposits`, `roa`, `roe`, `source_updated_at`, and "
            "`source_code` `FDIC_BANKS_INSTITUTIONS`. The RSSD and parent fields are emitted as null because the "
            "FDIC institutions feed does not carry them; the canonical shape reserves the columns so a future "
            "true-NIC source can populate them without a contract change.\n"
            "\n"
            "## The current-parent restriction\n"
            "\n"
            "Restricting to current-parent-only is one of the most consequential scope choices in the platform. "
            "NIC publishes much richer relationship data: predecessor and successor links, transformation "
            "events, multi-level ownership chains, and dated relationship windows. Each is useful and each adds "
            "join complexity that downstream consumers would have to understand. The restriction removes the "
            "temporal dimension entirely, so an institution has at most one current parent at any moment and a "
            "consumer reads a single column instead of reconstructing a graph. The cost is the inability to "
            "answer historical lineage questions; the gain is a join model that stays simple and stable.\n"
            "\n"
            "## Bronze layout and cadence\n"
            "\n"
            "The client writes a `.data.json` payload plus a metadata manifest under "
            "`data/raw/source=nic/ingestion_date=YYYY-MM-DD/<uuid>...`, with the manifest pointing the serving "
            "layer at the payload through `artifact_path`. The Airflow DAG `dag_ingest_nic` runs quarterly on "
            "`0 3 1 */3 *`, matching the cadence of institution-level disclosure. When no source URL is "
            "configured, the `nic` flow shows Not Activated in the pipeline status model "
            "([[Pipeline Status and Operational State]]). The Silver model that consumes this source, "
            "`stg_nic_current_parent`, narrows it further to identity and parent columns, in keeping with "
            "[[Bronze, Silver, Intermediate, Gold]]."
        ),
    },
    "dbt Model Inventory": {
        "cluster": "Warehouse Layer",
        "branch": "Data Plumbing",
        "summary": "The dbt project holds eleven models (four staging, one intermediate, four mart facts, two reference dimensions) plus one acquirer dimension built in the serving layer, one snapshot, and seven structural tests, materialised as views in staging and tables in marts.",
        "body": (
            "The dbt project under `dbt/` is intentionally small. The count is kept low so the lineage graph "
            "stays readable, which is the single most useful artefact for explaining the platform. The project "
            "name is `finlens_dbt` and it runs against the `finlens` profile.\n"
            "\n"
            "## Sources\n"
            "\n"
            "`dbt/models/staging/sources.yml` declares one source group named `raw`, pointing at the `raw` "
            "schema, with four tables: `fdic_failed_banks_raw`, `fred_observations_raw`, `fdic_qbp_raw`, and "
            "`nic_current_parent_raw`. Every staging model reads from this group rather than from a warehouse "
            "table directly.\n"
            "\n"
            "## Staging (Silver)\n"
            "\n"
            "Four staging models normalise each source into a typed canonical shape. `stg_fdic_failed_banks` "
            "projects bank identity, location, certificate number, acquirer, closing date, year, and assets. "
            "`stg_fred_observations` projects series id, date, value, and metric name. `stg_fdic_qbp` projects "
            "the eleven Stress Pulse columns (`quarter`, `net_income`, `roa`, `nim`, `problem_banks`, "
            "`asset_yield`, `funding_cost`, `noncurrent_rate`, `nco_rate`, `afs_losses`, `htm_losses`). "
            "`stg_nic_current_parent` narrows the institution feed to RSSD id, FDIC certificate number, "
            "institution name, and current-parent identity. Per the project config, everything in `staging` "
            "materialises as a `view`.\n"
            "\n"
            "## Intermediate\n"
            "\n"
            "The intermediate layer holds one model, `int_failures_with_macro_context`, currently a passthrough "
            "over the failures fact. It is kept as a deliberate placeholder for reusable joins that future "
            "marts will share; the layer exists in the architecture even when sparsely populated so that joins "
            "do not migrate into the marts and grow them into unmaintainable SQL. Intermediate also materialises "
            "as a `view`.\n"
            "\n"
            "## Marts (Gold)\n"
            "\n"
            "Four mart facts form the dashboard contract. `fct_bank_failures` is the failed-bank fact table. "
            "`fct_stress_pulse` is the industry-aggregate fact, reading from `stg_fdic_qbp`. "
            "`fct_financial_metrics` is the macro time-series fact, and it is the one model materialised as "
            "`incremental` with `unique_key=['series_id', 'date']`, because the FRED panel grows append-only and "
            "a full re-projection would be wasteful. `bank_quarterly_risk_facts` is the per-bank-quarter "
            "CAMELS-aligned risk panel at grain `(cert, quarter)` that backs the predictive subsystem. The "
            "marts config materialises non-incremental marts as `table`. A further Gold object, `dim_acquirer`, "
            "is an acquirer-by-decade rollup; in the local DuckDB build it is produced by the serving layer in "
            "`src/finlens/warehouse.py` rather than by a dbt model file.\n"
            "\n"
            "## Reference and snapshot\n"
            "\n"
            "The reference layer provides `dim_date` (a generated calendar dimension) and `dim_state` (a static "
            "state-code mapping). The snapshot `dbt/snapshots/dim_bank_snapshot.sql` captures slowly changing "
            "dimension behaviour over the failed-bank set using dbt's `check` strategy on the `bank_name` and "
            "`state` columns, keyed on `bank_id`, written to the `snapshots` target schema.\n"
            "\n"
            "## Tests\n"
            "\n"
            "The project declares seven structural tests. In `dbt/models/marts/schema.yml`: `bank_id` and "
            "`state` on `fct_bank_failures` are `not_null`, `series_id` on `fct_financial_metrics` is "
            "`not_null`, `quarter` on `fct_stress_pulse` is `not_null`, and `cert` and `quarter` on "
            "`bank_quarterly_risk_facts` are `not_null`. A seventh, singular test, "
            "`dbt/tests/assert_bank_quarterly_risk_facts_unique_grain.sql`, asserts the composite "
            "`(cert, quarter)` grain is unique. These are the structural-integrity layer of the "
            "[[Data Quality Strategy]] and sit alongside the [[Bronze, Silver, Intermediate, Gold]] flow."
        ),
    },
    "Why the DAGs Are Thin": {
        "cluster": "Orchestration",
        "branch": "Data Plumbing",
        "summary": "Every DAG is a thin BashOperator wrapper around a Python entry point with no XCom, no Python operators, and no Airflow-specific business logic, which keeps the orchestrator disposable and the logic identical between local runs and scheduled runs.",
        "body": (
            "Each DAG under `airflow/dags/` is a thin shell. The body of a DAG is a `BashOperator` that changes "
            "into the project directory and invokes a Python entry point through the project's virtual "
            "environment. There is no XCom, no `PythonOperator` carrying logic, and no Airflow-specific feature "
            "the underlying job depends on.\n"
            "\n"
            "## What the shells call\n"
            "\n"
            "The four ingestion DAGs each call `scripts/run_local_pipeline.py` with a single `--sources` value "
            "and `--skip-warehouse`. `dag_ingest_fdic` passes `--sources fdic`, `dag_ingest_fred` passes "
            "`--sources fred`, and the quarterly `dag_ingest_qbp` and `dag_ingest_nic` pass their respective "
            "source. `dag_transform_and_quality` calls the same runner with "
            "`--allow-missing-connectors --run-dbt-build --probe-platform --sync-postgres`, so the daily "
            "transform, the platform probes, and the Postgres sync are flags on one entry point rather than a "
            "tree of operators. `dag_sync_control_plane` shells out to collect Airflow run evidence and then "
            "calls `scripts/sync_control_plane_to_postgres.py`. The ML retraining DAG calls scripts under `ml/`.\n"
            "\n"
            "## Why thin\n"
            "\n"
            "The most common decay pattern in real Airflow deployments is the slow migration of business logic "
            "into operator parameters and inline Python callables. It starts because adding one rule to a DAG "
            "feels easier than adding it to the underlying script, and it ends with the same rule living in "
            "several places and a metric definition that cannot be changed without touching the orchestrator. "
            "Keeping the DAGs thin avoids that entirely: the command Airflow runs is the same command runnable "
            "on a laptop, which is the property described under [[Local Parity]].\n"
            "\n"
            "## Disposability\n"
            "\n"
            "Because no logic lives in the DAGs, the orchestrator is disposable. Migrating to Dagster, Prefect, "
            "or a managed scheduler would mean replacing the DAG shells, not rewriting the jobs. The shared "
            "`default_args` in `airflow/dags/common.py` set `retries=2` and a five-minute `retry_delay`; that "
            "conservative retry posture is affordable precisely because each ingestion is idempotent at the "
            "Bronze level (the UUID suffix prevents overwrite collisions) and the transformation step rebuilds "
            "deterministically. The flows these DAGs drive are tracked in "
            "[[Pipeline Status and Operational State]], and the transform DAG is what runs the "
            "[[Data Quality Strategy]] checks and the [[Reconciliation Against External Authority]] comparison.\n"
            "\n"
            "## Ordering only where it is real\n"
            "\n"
            "Most of the DAGs are single-task, because a one-source ingestion has nothing to order. The few "
            "places where ordering exists are the places where it is genuinely required: the ML retraining DAG "
            "sequences dataset build, training, a metric gate, and export so that a regressing model is blocked "
            "before it can be promoted. Expressing dependency only where a real precedence exists keeps the "
            "graphs honest and avoids inventing structure the work does not need, which is the same restraint "
            "applied to the source set in [[Source Policy Overview]]."
        ),
    },
    "Local Parity": {
        "cluster": "Orchestration",
        "branch": "Data Plumbing",
        "summary": "Everything the deployed platform runs is runnable locally without cloud credentials, using DuckDB as the warehouse, the local filesystem as Bronze, and the exact Python entry points the scheduled DAGs invoke.",
        "body": (
            "Local parity is the property that the platform runs end to end on a laptop, with no AWS, "
            "Snowflake, or other cloud credential, using the same code paths the deployed environment uses. It "
            "is treated as a hard requirement rather than a convenience.\n"
            "\n"
            "## The local substitutions\n"
            "\n"
            "Two components swap for credential-free equivalents. The warehouse target becomes DuckDB instead "
            "of Snowflake; the dbt `local` output in `dbt/profiles.yml` is a DuckDB profile keyed on "
            "`FINLENS_DUCKDB_PATH`, defaulting to `./.duckdb/finlens.duckdb`, while the `snowflake` output is "
            "selected only when cloud credentials are present. The orchestrator is replaced by direct invocation "
            "of the same entry points the DAGs call, since the DAGs themselves are thin shells over those scripts "
            "([[Why the DAGs Are Thin]]). Bronze storage is the VPS local filesystem tree under `data/raw/...` in "
            "every environment, with no cloud object store; a rotation policy retains one version per source.\n"
            "\n"
            "## The local build path\n"
            "\n"
            "In `mock` data mode, `src/finlens/warehouse.py` builds the DuckDB warehouse directly: it reads the "
            "latest Bronze artefact for each source, normalises into canonical frames, registers them, and "
            "creates the `raw.*` landing tables and the `marts.*` Gold tables (`fct_bank_failures`, "
            "`fct_financial_metrics`, `dim_acquirer`, `fct_stress_pulse`) in one pass. As it goes it updates the "
            "`bronze_to_silver`, `silver_to_gold`, and `gold_to_dashboards` flow statuses, so a local run "
            "populates the same operational state the deployed run does.\n"
            "\n"
            "## The developer entry points\n"
            "\n"
            "The repository ships PowerShell helpers for the common actions: `scripts/use_finlens_env.ps1` to "
            "activate the environment, `python scripts/run_local_pipeline.py --sources fdic` to ingest a "
            "source into the local DuckDB warehouse, `scripts/start_finlens.ps1` for the Streamlit app, "
            "`scripts/start_api.ps1` for the FastAPI service, and `scripts/smoke_test.ps1` for the smoke test. "
            "None of these need a cloud credential.\n"
            "\n"
            "## Why it matters\n"
            "\n"
            "Local parity is what makes the deployed claims checkable. A reviewer who cannot run the deployed "
            "stack can still clone the repository and watch the same flow that runs in production, which turns "
            "architectural claims into reproducible ones. It also keeps the two environments honest with each "
            "other: a behaviour that only works with cloud services would break local parity and be caught "
            "immediately. The same DuckDB and Snowflake split appears throughout "
            "[[Bronze, Silver, Intermediate, Gold]]."
        ),
    },
    "Reconciliation Against External Authority": {
        "cluster": "Quality and Reconciliation",
        "branch": "Controls",
        "summary": "Reconciliation compares the platform's Gold aggregates against the FDIC's own published QBP totals within a documented tolerance, turning a trust-me dashboard claim into a verifiable one, while being explicit that the guarantee is coarse-grained.",
        "body": (
            "Most dashboards make claims about data and ask the reader to trust them. Reconciliation makes a "
            "different kind of claim: it shows the platform's aggregate numbers next to the source authority's "
            "aggregate numbers and lets the difference speak. It is the strongest credibility control in the "
            "platform.\n"
            "\n"
            "## Why anchor to QBP\n"
            "\n"
            "The comparison anchors to the FDIC Quarterly Banking Profile for three reasons. It is the same "
            "agency that publishes the underlying institution-level data, so there is no cross-source taxonomy "
            "mismatch. The totals are computed at the agency rather than reconstructed by the platform, so the "
            "comparison is against an independent figure. And the quarterly cadence is a tractable comparison "
            "frequency that matches the [[FDIC Quarterly Banking Profile]] ingestion.\n"
            "\n"
            "## What is reconciled\n"
            "\n"
            "The panel reconciles total industry assets, total deposits, total equity, net income, and the "
            "problem-bank count. These map onto the amounts the QBP ingestion sums during normalisation "
            "(`ASSET`, `DEP`, `EQ`, `NETINC`), with the problem-bank count compared where the source carries "
            "it. Each comparison displays the platform value, the FDIC value, the absolute difference, and a "
            "tolerance. A difference inside tolerance renders green; a difference outside tolerance renders red "
            "and the surface explains the discrepancy rather than hiding it. The reconciliation runs as part of "
            "the daily dbt build and is exposed in the Reconciliation tab of the technical surface.\n"
            "\n"
            "## What it proves and what it does not\n"
            "\n"
            "The control is precise about its own scope. A green result proves that the platform's "
            "aggregate-level numbers match the FDIC's aggregate-level numbers within tolerance. It does not "
            "prove per-bank or per-period correctness; finer-grained values can still drift while the totals "
            "agree, so this is a coarse-grained guarantee by design. Stating that limitation explicitly is part "
            "of the control, not a caveat bolted onto it.\n"
            "\n"
            "## Where it sits among the controls\n"
            "\n"
            "Reconciliation is the outermost layer of the [[Data Quality Strategy]]. It asserts what is true by "
            "comparison to an external authority, which is a distinct kind of authority from the structural "
            "tests in dbt (true by construction) and the source-readiness checks in the ingestion clients (true "
            "about runtime configuration). It is also distinct from operational state: a run can reconcile "
            "cleanly and still have failed operationally, which is the separation drawn in "
            "[[Pipeline Status and Operational State]]."
        ),
    },
    "Data Quality Strategy": {
        "cluster": "Quality and Reconciliation",
        "branch": "Controls",
        "summary": "Data quality is split across four layers with distinct authority: source readiness at ingestion, structural integrity in dbt, distributional checks planned for when source history is deep enough, and reconciliation against an external authority.",
        "body": (
            "Quality responsibility is deliberately spread across four layers rather than concentrated in one "
            "tool. Each layer asserts what it has the most natural authority over, so a failure in one is "
            "locally recoverable instead of globally fatal. The most common mistake the design avoids is mixing "
            "all four concerns into a single checker.\n"
            "\n"
            "## Layer one: source readiness\n"
            "\n"
            "Each ingestion client validates its configuration before doing network work. The FRED client calls "
            "`Settings.require(\"fred_api_key\")`, the QBP client requires `fdic_qbp_source_url`, and the NIC "
            "client requires `nic_current_parent_source_url`; a missing value raises rather than producing an "
            "empty Bronze artefact that would look like success. The settings layer also treats common "
            "placeholder strings (for example `your-value-here` and `changeme`) as missing through "
            "`is_missing_or_placeholder`, so a half-filled `.env` does not silently become active configuration.\n"
            "\n"
            "## Layer two: structural integrity in dbt\n"
            "\n"
            "`dbt/models/marts/schema.yml` declares structural tests that are true by construction: `bank_id` "
            "and `state` `not_null` on `fct_bank_failures`, `series_id` `not_null` on `fct_financial_metrics`, "
            "and `quarter` `not_null` on `fct_stress_pulse`. These run during the daily dbt build and assert "
            "shape, nullness, and key presence at the marts boundary described in "
            "[[Bronze, Silver, Intermediate, Gold]].\n"
            "\n"
            "## Layer three: distributional checks\n"
            "\n"
            "Distributional and statistical checks are reserved for later hardening, once a source has enough "
            "history to make value-range and distribution-shape assertions meaningful. The intent is "
            "lightweight platform checkpoints rather than a heavyweight validation framework, added when the "
            "data justifies them rather than pre-emptively. This layer is described as planned in the platform "
            "documentation; the structural and reconciliation layers carry the load until it lands.\n"
            "\n"
            "## Layer four: reconciliation\n"
            "\n"
            "Reconciliation asserts what is true by comparison to an external authority, matching the platform's "
            "five Gold aggregates against the FDIC's published QBP totals within a documented tolerance on every "
            "dbt build. It is covered in full under [[Reconciliation Against External Authority]].\n"
            "\n"
            "## Why the split holds up\n"
            "\n"
            "No single layer is responsible for everything. Configuration problems surface at ingestion, "
            "structural problems surface in dbt, distributional problems will surface in the checkpoints, and "
            "consistency-with-source problems surface in reconciliation. Keeping the four separate is what makes "
            "a quality failure diagnosable, and it keeps quality distinct from operational state, which is "
            "tracked separately under [[Pipeline Status and Operational State]]."
        ),
    },
    "Pipeline Status and Operational State": {
        "cluster": "Quality and Reconciliation",
        "branch": "Controls",
        "summary": "Operational state is tracked separately from data quality through a seven-flow status model in pipeline_status.py, where each flow records a status, last-run timestamp, row count, and note, and unconfigured sources show Not Activated rather than a faked success.",
        "body": (
            "Operational state and data quality are orthogonal. A run can succeed operationally while producing "
            "data that fails quality checks, and a run can fail operationally while leaving previously-good data "
            "still queryable. The platform tracks the two separately, and this article is about the operational "
            "side.\n"
            "\n"
            "## The flow model\n"
            "\n"
            "`src/finlens/pipeline_status.py` defines seven flow keys in a fixed display order: `fdic`, `qbp`, "
            "`fred`, `nic` for the four ingestion legs, then `bronze_to_silver`, `silver_to_gold`, and "
            "`gold_to_dashboards` for the transformation legs. Each key has a human label and an associated "
            "source name in `FLOW_LABELS`, for example `fdic` renders as `FDIC -> Bronze` sourced from "
            "`FDIC BankFind`, and `gold_to_dashboards` renders as `Gold -> Dashboards` sourced from `Serving`.\n"
            "\n"
            "## What each flow records\n"
            "\n"
            "A flow record carries a status string, a `last_run` value, a `rows` count, and a free-text note, "
            "with an `updated_at` timestamp stamped automatically. State is persisted through the platform "
            "state store (`load_state` and `save_state`), and `update_flow_status` merges new fields into the "
            "existing record so a single leg can be updated without rewriting the whole model. The local "
            "warehouse build calls this directly: as `initialise_local_duckdb` rebuilds the canonical frames and "
            "the Gold marts, it moves `bronze_to_silver`, `silver_to_gold`, and `gold_to_dashboards` through "
            "Running and then Success with row counts like `4 contracts`, `4 views`, and `4 surfaces`.\n"
            "\n"
            "## Not Activated instead of faked\n"
            "\n"
            "A `DEFERRED_FLOWS` table gives `qbp` and `nic` an explicit Not Activated status when their source "
            "URL is absent, with a note that reconciliation or current-parent lineage is disabled rather than "
            "faked. `pipeline_status_rows` falls back to this deferred state when no live record exists, so the "
            "surface distinguishes between a leg that failed, a leg that has no run yet (Missing Data), and a "
            "leg that is intentionally inactive. This is the same honesty principle that the "
            "[[FDIC Quarterly Banking Profile]] and [[National Information Center]] articles describe at the "
            "source level.\n"
            "\n"
            "## Scope\n"
            "\n"
            "The model is deliberately small: a status, a timestamp, a row count, and a note. It is not a full "
            "observability platform and is not presented as one. It is the smallest layer that turns "
            "operational state into something visible from the user-facing Live Pipeline surface "
            "([[Streamlit Surfaces]]) without requiring a reviewer to log into Airflow, and it stays distinct "
            "from the quality controls in [[Data Quality Strategy]]."
        ),
    },
    "Streamlit Surfaces": {
        "cluster": "Serving",
        "branch": "Serving",
        "summary": "Streamlit serves three surfaces, an analytical business surface, a data-engineering surface, and an AI-engineering surface, plus a shared Wiki, all reading Gold only through a single data-access module, with no page touching Bronze, an ingestion client, or staging SQL.",
        "body": (
            "The platform serves three Streamlit surfaces plus a shared Wiki. The business surface presents "
            "analytical content to a banking and risk audience; the data-engineering surface presents pipeline "
            "and warehouse internals to a data-engineering audience; the AI-engineering surface presents the "
            "predictive subsystem to a machine-learning audience. The engineering surfaces carry the depth "
            "because that content is the primary signal for the audience the platform was built for.\n"
            "\n"
            "## The Gold-only rule\n"
            "\n"
            "Every Streamlit page reads Gold and only Gold. Pages read through "
            "`streamlit_app/lib/data.py`, which in turn reads through the warehouse helpers in "
            "`src/finlens/warehouse.py`. No page reads Bronze artefacts, calls an ingestion client at request "
            "time, or issues SQL against staging tables. The contract is structural: the helper modules expose "
            "only Gold-reading interfaces, and in `mock` data mode `read_table` first calls "
            "`initialise_local_duckdb` so the Gold tables exist before any page queries them. This is the same "
            "binding rule that drives [[Bronze, Silver, Intermediate, Gold]].\n"
            "\n"
            "## The business surface\n"
            "\n"
            "The business surface favours depth over breadth across its pages. Stress Pulse reads "
            "`fct_stress_pulse` for the industry-aggregate readings (profitability, asset quality, capital). "
            "Failure Forensics reads `fct_bank_failures` and `dim_acquirer` for the historical failure record. "
            "Macro Transmission reads `fct_financial_metrics` for the FRED series, with the interpretation "
            "guidance in [[How to Read Macro Indicators in This Surface]]. Early Warning scores currently "
            "operating institutions and is framed as analytical context rather than supervisory or investment "
            "guidance, and Bank Report compiles a single-institution view. The predictive modelling itself is "
            "presented on the AI-engineering surface.\n"
            "\n"
            "## The data-engineering surface\n"
            "\n"
            "The data-engineering surface is one page with six in-page sections that expose the engineering "
            "internals: a Live Pipeline view driven by [[Pipeline Status and Operational State]], a Data "
            "Quality view tied to the [[Data Quality Strategy]] and [[Reconciliation Against External "
            "Authority]], Source Contracts derived from the Bronze landing tree, an Engineering Stack view, an "
            "Administration view, and an Architecture Decisions view. Helper functions in "
            "`src/finlens/evidence.py` feed several of these by reading the Bronze landing tree, the local "
            "DuckDB table inventory, and the dbt run artefacts, so the views reflect actual on-disk state "
            "rather than static copy. The machine-facing counterpart to these read paths is described under "
            "[[FastAPI Endpoints]].\n"
            "\n"
            "## The AI-engineering surface\n"
            "\n"
            "The AI-engineering surface is one page with eight in-page sections covering the predictive "
            "subsystem: the per-bank-quarter risk panel, the model and its validation, and the supporting "
            "evidence. The shared Wiki this article belongs to is reachable from every surface rather than "
            "owned by any single one.\n"
            "\n"
            "## Demo mode and graceful degradation\n"
            "\n"
            "The serving layer is built to render even when a live source has not been ingested. In the default "
            "`mock` data mode the warehouse is built from the latest ingested Bronze artefacts, not from "
            "fabricated data; the bundled demo dataset is only a fresh-clone fallback that the warehouse helpers "
            "substitute for the failures, metrics, and stress-pulse frames when no Bronze artefact is present at "
            "all. In `live` data mode an absent QBP artefact yields an empty frame rather than substituted data. "
            "A `stress_pulse_source_mode` helper reports whether a surface "
            "is showing live, demo, or pending data, so the page can label its own provenance instead of "
            "silently mixing the two. That labelling is the surface-level expression of the honesty principle "
            "carried through [[Pipeline Status and Operational State]] and [[Data Quality Strategy]]."
        ),
    },
    "FastAPI Endpoints": {
        "cluster": "Serving",
        "branch": "Serving",
        "summary": "FastAPI is the machine-facing control plane: health probes for monitoring, telemetry intake and summary, and thin Gold-backed read endpoints for failures, a single bank, and a single FRED series, with validation in Pydantic and no business logic in the service.",
        "body": (
            "FastAPI is the machine-facing side of serving. Where Streamlit renders for humans, FastAPI exposes "
            "a stable JSON interface for monitoring tools and programmatic consumers. It is deliberately small "
            "and organised around three concerns.\n"
            "\n"
            "## Health\n"
            "\n"
            "`/health` and `/healthz` return service-level health for monitoring tools. Uptime Kuma is the "
            "current consumer; it probes `/healthz` and raises through its own notification channels when a "
            "probe fails. These endpoints are cheap and have no data dependency, so a healthy probe means the "
            "service is up, not that the data is fresh; freshness is a separate concern tracked in "
            "[[Pipeline Status and Operational State]].\n"
            "\n"
            "## Telemetry\n"
            "\n"
            "`/telemetry/events` accepts page-view and interaction events from the Streamlit surface and records "
            "them on the local request path. `/telemetry/summary` returns a rolling summary for display in the "
            "technical surface. Local capture is kept fast on the request path; aggregation runs on its own "
            "schedule and is mirrored to Postgres out of band, which is the split described in "
            "[[Edge and Operations]].\n"
            "\n"
            "## Read endpoints\n"
            "\n"
            "Three read endpoints expose Gold marts: `/failures` returns the failed-bank list, "
            "`/banks/{bank_id}` returns a single bank record, and `/metrics/{series_id}` returns a single FRED "
            "series. They read the same Gold tables the Streamlit surface reads "
            "(`fct_bank_failures`, `fct_financial_metrics`), so the API and the dashboard never disagree about "
            "what a number is.\n"
            "\n"
            "## Why the service is thin\n"
            "\n"
            "The read endpoints carry no business logic. Metric definitions live in dbt, not in the service, so "
            "the API is just the read shape over the warehouse output, with Pydantic validating request and "
            "response models. Keeping logic out of the service keeps it disposable in the same spirit as the "
            "thin DAGs ([[Why the DAGs Are Thin]]), and keeps the single source of truth for any metric inside "
            "[[Bronze, Silver, Intermediate, Gold]].\n"
            "\n"
            "## Validation and contract stability\n"
            "\n"
            "Pydantic request and response models give two things at once: automatic OpenAPI documentation and "
            "validation at the boundary, so a malformed request is rejected before it reaches any read logic and "
            "a response that does not match its declared shape fails loudly rather than serving a surprising "
            "payload. Because the response models are defined over Gold columns, a change to a mart that would "
            "alter the JSON shape surfaces as a model mismatch, which is the same containment guarantee the "
            "Gold-only rule gives the Streamlit pages in [[Streamlit Surfaces]]. The net effect is a small, "
            "stable, self-documenting read surface that consumers can depend on without coupling to the "
            "warehouse internals."
        ),
    },
    "Edge and Operations": {
        "cluster": "Serving",
        "branch": "Serving",
        "summary": "Cloudflare provides the public edge (TLS, DNS, and optional Turnstile bot protection on the telemetry POST), and a Postgres control plane receives telemetry mirrored from local state every thirty minutes so aggregation runs off the request path.",
        "body": (
            "The edge and the control plane sit on either side of the serving layer: Cloudflare in front of the "
            "public hostname, Postgres behind it for out-of-band aggregation.\n"
            "\n"
            "## Cloudflare at the edge\n"
            "\n"
            "Cloudflare fronts the public domain `surya.vaddhiparthy.com`. It handles TLS termination, DNS, and "
            "optional Turnstile bot protection on the telemetry POST endpoint. The relevant configuration keys "
            "are `CLOUDFLARE_TURNSTILE_SITE_KEY` and `CLOUDFLARE_TURNSTILE_SECRET_KEY` for the bot check, plus "
            "`CLOUDFLARE_ACCOUNT_ID`, `CLOUDFLARE_ZONE_ID`, and `CLOUDFLARE_API_TOKEN` for account and zone "
            "management. Cloudflare was chosen for free-tier coverage, DNS simplicity, and the Turnstile "
            "challenge on the one write-facing public endpoint, which is the telemetry intake described in "
            "[[FastAPI Endpoints]].\n"
            "\n"
            "## Postgres control plane\n"
            "\n"
            "Telemetry is captured locally on the fast request path and mirrored to a Postgres database for "
            "analytical aggregation. The `dag_sync_control_plane` DAG runs every thirty minutes (cron "
            "`*/30 * * * *`): it collects Airflow run evidence and then runs "
            "`scripts/sync_control_plane_to_postgres.py`. The Postgres target is configured through "
            "`POSTGRES_SYNC_DSN` and `POSTGRES_SYNC_SCHEMA` (default `finlens`), and "
            "`probe_postgres_sync` in `src/finlens/platform_probes.py` reports the target as Scaffolded when no "
            "DSN is set and Ready when a connection succeeds.\n"
            "\n"
            "## Why capture and aggregation are split\n"
            "\n"
            "Local capture has to stay fast on the request path, while aggregation can run on its own schedule "
            "without affecting page latency. Splitting them means a slow or unreachable Postgres never degrades "
            "the user-facing experience; the worst case is that aggregation lags by one sync interval. The "
            "broader operational layout this fits into, including Caddy and Uptime Kuma, is covered under "
            "[[Deployment Topology]].\n"
            "\n"
            "## Turnstile on the one write endpoint\n"
            "\n"
            "Of the public endpoints, only telemetry intake accepts a write, so it is the only one that needs "
            "abuse protection. Turnstile is applied there rather than across the whole surface, which keeps "
            "read paths and health probes free of friction while putting a challenge in front of the single "
            "endpoint that could be flooded. This is a deliberately narrow application of bot protection: "
            "protect what can be abused, leave the rest open.\n"
            "\n"
            "## Probing the control plane\n"
            "\n"
            "The Postgres leg is observable through `probe_postgres_sync`, which opens a short-timeout "
            "connection and runs a trivial query, returning Ready on success, Failed with the error detail on a "
            "connection problem, and Scaffolded when no DSN is configured. That probe feeds the same platform "
            "stack view that reports VPS local storage, dbt, Airflow, and Snowflake state, so the edge and control-plane "
            "components show up alongside the rest of the stack in the technical surface "
            "([[Streamlit Surfaces]])."
        ),
    },
    "Deployment Topology": {
        "cluster": "Operations",
        "branch": "Operations",
        "summary": "The platform deploys as a small set of Docker Compose containers behind Caddy and Cloudflare, with Streamlit serving the user app under a subpath, FastAPI serving health and read endpoints, Uptime Kuma monitoring reachability, and Postgres holding control-plane state.",
        "body": (
            "The deployed platform is a small set of containers, kept small on purpose so the operational story "
            "stays comprehensible.\n"
            "\n"
            "## The public route\n"
            "\n"
            "The public route is `https://surya.vaddhiparthy.com/finlens/`. The application is served under a "
            "subpath of the main portfolio rather than at a root host. Streamlit is naturally simpler at a root "
            "path, so the subpath needs careful Caddy reverse-proxy configuration to handle the WebSocket and "
            "asset paths Streamlit uses; that complexity is accepted in exchange for keeping the project under "
            "one portfolio domain.\n"
            "\n"
            "## The containers\n"
            "\n"
            "Streamlit serves the three user-facing surfaces ([[Streamlit Surfaces]]). FastAPI serves the "
            "machine-facing health and read endpoints ([[FastAPI Endpoints]]). Uptime Kuma monitors service "
            "reachability against the FastAPI `/healthz` endpoint and alerts through its own channels. Postgres "
            "holds the control-plane state synchronised from local telemetry ([[Edge and Operations]]). Caddy "
            "reverse-proxies from the public hostname to the Streamlit and FastAPI containers, and Cloudflare "
            "sits in front for TLS, DNS, and the Turnstile challenge.\n"
            "\n"
            "## Warehouse target in deployment\n"
            "\n"
            "DuckDB is the warehouse of record in both environments: the dbt project defaults to its `local` "
            "DuckDB output, and the local build in `src/finlens/warehouse.py` is what populates the marts the "
            "surfaces read. Snowflake remains wired as an optional `snowflake` dbt output that is selected only "
            "when Snowflake credentials are present, but the Snowflake trial has expired, so it is currently "
            "aspirational rather than the live target; MotherDuck is the $0 cloud path that keeps the DuckDB "
            "engine in the cloud without a paid warehouse. Either way the local DuckDB path is the parity "
            "property covered under [[Local Parity]]. The `probe_platform_stack` helper in "
            "`src/finlens/platform_probes.py` reports the live state of VPS local raw storage, dbt, Airflow, Snowflake, and "
            "Postgres, marking each as Scaffolded, Ready, Unavailable, or Failed depending on configuration and "
            "reachability; an unconfigured Snowflake therefore shows as Scaffolded rather than as a live "
            "warehouse.\n"
            "\n"
            "## Orchestration choice\n"
            "\n"
            "The platform deploys with Docker Compose at the current scale. A managed container orchestrator "
            "(for example ECS or Cloud Run) is a possible later move if operational requirements grow, but "
            "Compose is sufficient now. Secrets for all of these components are kept out of source control, as "
            "described under [[Configuration and Secrets]].\n"
            "\n"
            "## How environments diverge and converge\n"
            "\n"
            "The deployed and local environments diverge in a small number of places and converge everywhere "
            "else. The warehouse is DuckDB in both (Snowflake is an optional output, not the live target, since "
            "the trial has expired); Bronze is the VPS local filesystem in every environment (no cloud object "
            "store, one retained version per source); and scheduling is Airflow in deployment versus direct script "
            "invocation locally. Everything else, the ingestion clients, the dbt "
            "models, the Gold contract, and the serving code, is identical, which is what makes the [[Local "
            "Parity]] property hold. A reviewer can therefore reproduce the deployed behaviour on a laptop and "
            "trust that what they see locally matches what runs in production.\n"
            "\n"
            "## Observing the deployed stack\n"
            "\n"
            "Beyond Uptime Kuma's reachability checks, the technical surface reads `probe_platform_stack` to "
            "show the live configuration and reachability of each external dependency. Each probe degrades "
            "gracefully: a component with no credentials reports Scaffolded, a reachable one reports Ready, an "
            "uninstalled client reports Unavailable, and a failed connection reports Failed with detail. This "
            "means the deployment view tells the truth about partial configuration rather than presenting an "
            "all-or-nothing picture, in keeping with [[Pipeline Status and Operational State]]."
        ),
    },
    "Configuration and Secrets": {
        "cluster": "Operations",
        "branch": "Operations",
        "summary": "Configuration is centralised in a pydantic Settings model loaded from .env locally and from deployment secrets in production, with required-value checks, placeholder detection, and masking so credentials never appear in code, logs, or screenshots.",
        "body": (
            "All configuration flows through one place: the `Settings` model in `src/finlens/config.py`, built "
            "on `pydantic-settings`. Values come from environment variables, loaded from `.env` for local "
            "development and from deployment secrets in production. Secrets never appear in source code, "
            "markdown, SQL, notebooks, screenshots, or logs.\n"
            "\n"
            "## What is configured\n"
            "\n"
            "The model holds the full configuration surface: the FRED API key and base URL "
            "(`FRED_API_KEY`, `FRED_BASE_URL`) and the series list (`FRED_SERIES_IDS`); the QBP and NIC source "
            "URLs (`FDIC_QBP_SOURCE_URL`, `NIC_CURRENT_PARENT_SOURCE_URL`) and the failed-bank URL "
            "(`FDIC_FAILED_BANKS_URL`); Snowflake "
            "account, user, password, role, the two warehouse names, and the four database names "
            "(`FINLENS_RAW`, `FINLENS_STAGING`, `FINLENS_INTERMEDIATE`, `FINLENS_MARTS`); the Postgres sync DSN "
            "and schema; and the Cloudflare account, zone, token, and Turnstile values. Runtime behaviour keys "
            "such as `FINLENS_ENVIRONMENT`, `FINLENS_DATA_MODE`, and `FINLENS_ACTIVE_SOURCES` live here too.\n"
            "\n"
            "## Validation and safety helpers\n"
            "\n"
            "The model carries three safety helpers. `require(*keys)` raises a clear error listing any missing "
            "values, and the ingestion clients call it before doing network work, which is the source-readiness "
            "layer of the [[Data Quality Strategy]]. `is_missing_or_placeholder` treats common placeholder "
            "strings such as `changeme` and `your-value-here` as if they were unset, so a half-filled "
            "configuration cannot quietly become active. `as_masked_dict` renders configuration for display "
            "with any key containing `key`, `token`, `password`, or `secret` masked as `***` and unset values "
            "shown as `<unset>`, which is what lets the technical surface show configuration state without "
            "leaking a credential.\n"
            "\n"
            "## Why environment configuration\n"
            "\n"
            "Source-control history is permanent. Once a secret lands in version control it has to be treated as "
            "compromised, so environment configuration is the minimum-friction location that does not carry "
            "that risk. A dedicated secrets manager (AWS Secrets Manager or HashiCorp Vault) is a sensible later "
            "refinement, but it would itself need credentials to reach, so the current `.env` and "
            "deployment-secrets approach is the right fit for the present scale. These values back every "
            "external component in [[Deployment Topology]] and [[Edge and Operations]].\n"
            "\n"
            "## One model, cached and typed\n"
            "\n"
            "The configuration is loaded once. `get_settings` is wrapped in `lru_cache`, so the model is parsed "
            "and validated a single time per process and every module reads the same typed instance instead of "
            "calling `os.environ` ad hoc. Typing matters here: a value like the telemetry-enabled flag is a real "
            "boolean and the active-source list is parsed into a list through a property, so consumers never "
            "re-parse a string or guess at a default. Convenience properties such as `fred_series_id_list` "
            "and `active_source_list` keep the parsing logic in one place rather than scattered "
            "across the clients that depend on it, which is the same single-source-of-truth discipline applied "
            "to metrics in [[Bronze, Silver, Intermediate, Gold]]."
        ),
    },
    "How to Read Macro Indicators in This Surface": {
        "cluster": "Macro & Markets",
        "branch": "Business Concepts",
        "summary": "The Macro Transmission surface presents the six configured FRED series under three framings, current value, trend, and cross-indicator, and deliberately avoids collapsing them into a single composite so that agreement and disagreement between indicators stay visible.",
        "body": (
            "The Macro Transmission surface reads the FRED series from the Gold mart `fct_financial_metrics` "
            "and presents them under three framings. Each framing answers a different question, and the choice "
            "of which to use depends on what the reader is trying to learn. The underlying series and the "
            "mechanism each one captures are documented in [[FRED and ALFRED]].\n"
            "\n"
            "## Current-value framing\n"
            "\n"
            "The current-value framing answers where conditions are now. Each series is shown with its most "
            "recent value, the change from the prior reading, and a short statistical context such as a "
            "percentile rank against its own history. This is the right framing for the current state without "
            "time-series interpretation: it tells the reader the level, not the path.\n"
            "\n"
            "## Trend framing\n"
            "\n"
            "The trend framing answers how conditions got here. Each series is drawn over a configurable time "
            "window with reference markers for prior banking-stress episodes (the 2008 global crisis and the "
            "2023 regional-bank shock). This is the right framing for seeing the "
            "trajectory and for placing the current reading against historical analogues.\n"
            "\n"
            "## Cross-indicator framing\n"
            "\n"
            "The cross-indicator framing answers whether the indicators agree. Multiple series are placed on a "
            "shared time axis, normalised either by z-score against their own history or by percentile rank so "
            "that series in different units become comparable. Agreement across indicators is evidence of a "
            "coherent reading; disagreement is evidence of ambiguity, and the ambiguity is itself informative.\n"
            "\n"
            "## Why no single composite\n"
            "\n"
            "The surface deliberately does not collapse the six series into one composite index. A composite is "
            "convenient but it hides the disagreement information that is often the most analytically "
            "interesting signal. The one composite shown, the Chicago Fed NFCI, is included as a published "
            "third-party index rather than as something derived on the platform, and it is read alongside its "
            "components rather than as a black box. The stance throughout is that macro data is interpretive "
            "context, not predictive content: a reader should leave with a clearer view of the environment "
            "banking operates in, not a forecast. The banking metrics these indicators provide context for are "
            "read on the Stress Pulse surface described under [[Streamlit Surfaces]]."
        ),
    },
}
