CREATE OR REPLACE PIPE FINLENS_RAW.PUBLIC.FRED_PIPE
  AUTO_INGEST = TRUE
AS
COPY INTO FINLENS_RAW.PUBLIC.FRED_OBSERVATIONS_RAW (raw_data, source_system, ingestion_timestamp, file_name)
FROM (
  SELECT
    PARSE_JSON($1),
    'fred',
    CURRENT_TIMESTAMP(),
    METADATA$FILENAME
  FROM @finlens_raw_stage/source=fred/
)
FILE_FORMAT = (TYPE = JSON);
