[theme]
base = "dark"
primaryColor = "#539bf5"
backgroundColor = "#22272e"
secondaryBackgroundColor = "#1b2026"
textColor = "#cdd9e5"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
